# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-22 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180517_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageprojectsdescription',
            name='tab_title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок закладки'),
        ),
    ]
