# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_pageprojectsdescription_tab_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tab_title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок закладки'),
        ),
    ]
