# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-22 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_auto_20180727_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='tab_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
