# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-22 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180606_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='interiordesign',
            name='tab_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
