# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-22 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_interiordesign_tab_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interiordesign',
            name='tab_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
