# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-06 19:59
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GypsumCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категорія ліпнини',
                'verbose_name_plural': 'Категорії ліпнини',
            },
        ),
        migrations.CreateModel(
            name='GypsumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='products_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фото ліпнини',
                'verbose_name_plural': 'Фотки ліпнини',
            },
        ),
        migrations.CreateModel(
            name='GypsumProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gypsumProducts.GypsumCategory')),
            ],
            options={
                'verbose_name': 'Ліпнина',
                'verbose_name_plural': 'Ліпнина',
            },
        ),
        migrations.CreateModel(
            name='PageGypsumDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('sub_title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=128, null=True)),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Опис сторінки проекти',
                'verbose_name_plural': 'Опис сторінки проектиу',
            },
        ),
        migrations.AddField(
            model_name='gypsumimage',
            name='gypsum_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gypsumProducts.GypsumProduct'),
        ),
    ]
