# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-09 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gypsumProducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagegypsumdescription',
            options={'verbose_name': 'Опис сторінки ліпнина', 'verbose_name_plural': 'Опис сторінки ліпнина'},
        ),
    ]
