# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-21 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gypsumProducts', '0003_auto_20180809_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='gypsumproduct',
            name='gypsum_3d_model',
            field=models.FileField(blank=True, default=None, null=True, upload_to='gypsum_3dmodels/'),
        ),
    ]
